/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedVendorsRouteImport } from './routes/_authenticated/vendors'
import { Route as AuthenticatedRawMaterialsRouteImport } from './routes/_authenticated/raw-materials'
import { Route as AuthenticatedProductsRouteImport } from './routes/_authenticated/products'
import { Route as AuthenticatedProductionRouteImport } from './routes/_authenticated/production'
import { Route as AuthenticatedPartsRouteImport } from './routes/_authenticated/parts'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedProductionNewRouteImport } from './routes/_authenticated/production.new'
import { Route as AuthenticatedProductsIdBomRouteImport } from './routes/_authenticated/products.$id.bom'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedVendorsRoute = AuthenticatedVendorsRouteImport.update({
  id: '/vendors',
  path: '/vendors',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRawMaterialsRoute =
  AuthenticatedRawMaterialsRouteImport.update({
    id: '/raw-materials',
    path: '/raw-materials',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProductsRoute = AuthenticatedProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProductionRoute = AuthenticatedProductionRouteImport.update({
  id: '/production',
  path: '/production',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPartsRoute = AuthenticatedPartsRouteImport.update({
  id: '/parts',
  path: '/parts',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProductionNewRoute =
  AuthenticatedProductionNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => AuthenticatedProductionRoute,
  } as any)
const AuthenticatedProductsIdBomRoute =
  AuthenticatedProductsIdBomRouteImport.update({
    id: '/$id/bom',
    path: '/$id/bom',
    getParentRoute: () => AuthenticatedProductsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/parts': typeof AuthenticatedPartsRoute
  '/production': typeof AuthenticatedProductionRouteWithChildren
  '/products': typeof AuthenticatedProductsRouteWithChildren
  '/raw-materials': typeof AuthenticatedRawMaterialsRoute
  '/vendors': typeof AuthenticatedVendorsRoute
  '/production/new': typeof AuthenticatedProductionNewRoute
  '/products/$id/bom': typeof AuthenticatedProductsIdBomRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/parts': typeof AuthenticatedPartsRoute
  '/production': typeof AuthenticatedProductionRouteWithChildren
  '/products': typeof AuthenticatedProductsRouteWithChildren
  '/raw-materials': typeof AuthenticatedRawMaterialsRoute
  '/vendors': typeof AuthenticatedVendorsRoute
  '/production/new': typeof AuthenticatedProductionNewRoute
  '/products/$id/bom': typeof AuthenticatedProductsIdBomRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/parts': typeof AuthenticatedPartsRoute
  '/_authenticated/production': typeof AuthenticatedProductionRouteWithChildren
  '/_authenticated/products': typeof AuthenticatedProductsRouteWithChildren
  '/_authenticated/raw-materials': typeof AuthenticatedRawMaterialsRoute
  '/_authenticated/vendors': typeof AuthenticatedVendorsRoute
  '/_authenticated/production/new': typeof AuthenticatedProductionNewRoute
  '/_authenticated/products/$id/bom': typeof AuthenticatedProductsIdBomRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/parts'
    | '/production'
    | '/products'
    | '/raw-materials'
    | '/vendors'
    | '/production/new'
    | '/products/$id/bom'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/parts'
    | '/production'
    | '/products'
    | '/raw-materials'
    | '/vendors'
    | '/production/new'
    | '/products/$id/bom'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/dashboard'
    | '/_authenticated/parts'
    | '/_authenticated/production'
    | '/_authenticated/products'
    | '/_authenticated/raw-materials'
    | '/_authenticated/vendors'
    | '/_authenticated/production/new'
    | '/_authenticated/products/$id/bom'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/vendors': {
      id: '/_authenticated/vendors'
      path: '/vendors'
      fullPath: '/vendors'
      preLoaderRoute: typeof AuthenticatedVendorsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/raw-materials': {
      id: '/_authenticated/raw-materials'
      path: '/raw-materials'
      fullPath: '/raw-materials'
      preLoaderRoute: typeof AuthenticatedRawMaterialsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/products': {
      id: '/_authenticated/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof AuthenticatedProductsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/production': {
      id: '/_authenticated/production'
      path: '/production'
      fullPath: '/production'
      preLoaderRoute: typeof AuthenticatedProductionRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/parts': {
      id: '/_authenticated/parts'
      path: '/parts'
      fullPath: '/parts'
      preLoaderRoute: typeof AuthenticatedPartsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/production/new': {
      id: '/_authenticated/production/new'
      path: '/new'
      fullPath: '/production/new'
      preLoaderRoute: typeof AuthenticatedProductionNewRouteImport
      parentRoute: typeof AuthenticatedProductionRoute
    }
    '/_authenticated/products/$id/bom': {
      id: '/_authenticated/products/$id/bom'
      path: '/$id/bom'
      fullPath: '/products/$id/bom'
      preLoaderRoute: typeof AuthenticatedProductsIdBomRouteImport
      parentRoute: typeof AuthenticatedProductsRoute
    }
  }
}

interface AuthenticatedProductionRouteChildren {
  AuthenticatedProductionNewRoute: typeof AuthenticatedProductionNewRoute
}

const AuthenticatedProductionRouteChildren: AuthenticatedProductionRouteChildren =
  {
    AuthenticatedProductionNewRoute: AuthenticatedProductionNewRoute,
  }

const AuthenticatedProductionRouteWithChildren =
  AuthenticatedProductionRoute._addFileChildren(
    AuthenticatedProductionRouteChildren,
  )

interface AuthenticatedProductsRouteChildren {
  AuthenticatedProductsIdBomRoute: typeof AuthenticatedProductsIdBomRoute
}

const AuthenticatedProductsRouteChildren: AuthenticatedProductsRouteChildren = {
  AuthenticatedProductsIdBomRoute: AuthenticatedProductsIdBomRoute,
}

const AuthenticatedProductsRouteWithChildren =
  AuthenticatedProductsRoute._addFileChildren(
    AuthenticatedProductsRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedPartsRoute: typeof AuthenticatedPartsRoute
  AuthenticatedProductionRoute: typeof AuthenticatedProductionRouteWithChildren
  AuthenticatedProductsRoute: typeof AuthenticatedProductsRouteWithChildren
  AuthenticatedRawMaterialsRoute: typeof AuthenticatedRawMaterialsRoute
  AuthenticatedVendorsRoute: typeof AuthenticatedVendorsRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedPartsRoute: AuthenticatedPartsRoute,
  AuthenticatedProductionRoute: AuthenticatedProductionRouteWithChildren,
  AuthenticatedProductsRoute: AuthenticatedProductsRouteWithChildren,
  AuthenticatedRawMaterialsRoute: AuthenticatedRawMaterialsRoute,
  AuthenticatedVendorsRoute: AuthenticatedVendorsRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
