-- commit_production: atomic production commit
-- Inserts production_batches row, inserts production_batch_parts junction rows,
-- decrements part_batches.quantity per allocation, and recomputes parts.current_stock.
-- Returns the new production_batches.id and batch_number.
--
-- Picks is JSONB: [{ "part_batch_id": "uuid", "quantity_used": 12.5 }, ...]
-- Guard: if any part_batch would go negative, raises an exception (caller treats as 4xx).
-- ponytail: this exists to prevent read-then-write over-consumption across concurrent wizard runs.

CREATE OR REPLACE FUNCTION public.commit_production(
  p_product_id          UUID,
  p_quantity_produced   INTEGER,
  p_production_date     DATE,
  p_expected_raw_kg     NUMERIC,
  p_actual_raw_kg       NUMERIC,
  p_notes               TEXT,
  p_picks               JSONB
)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_batch_id        UUID;
  v_batch_number    TEXT;
  v_part_id         UUID;
  v_quantity_used   NUMERIC;
  v_remaining       NUMERIC;
  v_part_updates    JSONB := '[]'::jsonb;
  v_pick            JSONB;
  v_part_totals     JSONB := '{}'::jsonb;
  v_part_total      NUMERIC;
BEGIN
  IF p_picks IS NULL OR jsonb_typeof(p_picks) <> 'array' OR jsonb_array_length(p_picks) = 0 THEN
    RAISE EXCEPTION 'picks must be a non-empty array';
  END IF;

  -- 1. Pre-flight: every picked batch must have enough remaining.
  FOR v_pick IN SELECT * FROM jsonb_array_elements(p_picks)
  LOOP
    SELECT pb.part_id,
           pb.quantity - COALESCE((
             SELECT SUM(pbp.quantity_used)
             FROM public.production_batch_parts pbp
             WHERE pbp.part_batch_id = (v_pick->>'part_batch_id')::uuid
           ), 0)
      INTO v_part_id, v_remaining
      FROM public.part_batches pb
     WHERE pb.id = (v_pick->>'part_batch_id')::uuid
       AND NOT pb.is_blocked;
    IF NOT FOUND THEN
      RAISE EXCEPTION 'part_batch % not found or blocked', v_pick->>'part_batch_id';
    END IF;
    v_quantity_used := (v_pick->>'quantity_used')::numeric;
    IF v_remaining < v_quantity_used THEN
      RAISE EXCEPTION 'part_batch % has only % remaining, requested %', v_pick->>'part_batch_id', v_remaining, v_quantity_used;
    END IF;

    -- Aggregate quantity per part_id so we can update parts.current_stock in one pass.
    v_part_total := COALESCE((v_part_totals->>v_part_id::text)::numeric, 0) + v_quantity_used;
    v_part_totals := jsonb_set(v_part_totals, ARRAY[v_part_id::text], to_jsonb(v_part_total));
  END LOOP;

  -- 2. Insert production_batches row.
  INSERT INTO public.production_batches (
    batch_number,
    product_id,
    quantity_produced,
    expected_raw_material_kg,
    actual_raw_material_kg,
    production_date,
    status,
    notes
  ) VALUES (
    '',                 -- auto-generated by trigger
    p_product_id,
    p_quantity_produced,
    p_expected_raw_kg,
    p_actual_raw_kg,
    COALESCE(p_production_date, CURRENT_DATE),
    'completed',
    p_notes
  )
  RETURNING id, batch_number INTO v_batch_id, v_batch_number;

  -- 3. Insert junction rows.
  FOR v_pick IN SELECT * FROM jsonb_array_elements(p_picks)
  LOOP
    INSERT INTO public.production_batch_parts (
      production_batch_id,
      part_batch_id,
      quantity_used
    ) VALUES (
      v_batch_id,
      (v_pick->>'part_batch_id')::uuid,
      (v_pick->>'quantity_used')::numeric
    );
  END LOOP;

  -- 4. Decrement part_batches.quantity (atomic SQL update — no read-then-write).
  FOR v_pick IN SELECT * FROM jsonb_array_elements(p_picks)
  LOOP
    UPDATE public.part_batches
       SET quantity = quantity - (v_pick->>'quantity_used')::numeric
     WHERE id = (v_pick->>'part_batch_id')::uuid;
  END LOOP;

  -- 5. Refresh parts.current_stock from the new part_batches reality.
  FOR v_part_id, v_part_total IN SELECT * FROM jsonb_each_text(v_part_totals)
  LOOP
    UPDATE public.parts p
       SET current_stock = COALESCE((
             SELECT SUM(pb.quantity) - COALESCE((
               SELECT SUM(pbp.quantity_used)
               FROM public.production_batch_parts pbp
               WHERE pbp.part_batch_id IN (SELECT id FROM public.part_batches WHERE part_id = p.id)
             ), 0)
             FROM public.part_batches pb
             WHERE pb.part_id = p.id
           ), 0)
     WHERE p.id = v_part_id::uuid;
  END LOOP;

  RETURN jsonb_build_object('id', v_batch_id, 'batch_number', v_batch_number);
END;
$$;

GRANT EXECUTE ON FUNCTION public.commit_production(UUID, INTEGER, DATE, NUMERIC, NUMERIC, TEXT, JSONB) TO authenticated;

-- get_part_availability RPC: planning + wizard compute available stock from per-batch rollup in one round trip.
-- Returns: { part_id, available, batches: [{ part_batch_id, batch_number, quantity, remaining }] }
CREATE OR REPLACE FUNCTION public.get_part_availability(p_part_ids UUID[])
RETURNS JSONB
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
  SELECT COALESCE(jsonb_agg(row), '[]'::jsonb)
  FROM (
    SELECT jsonb_build_object(
      'part_id', p.id,
      'part_name', p.part_name,
      'available', COALESCE((
        SELECT SUM(pb.quantity) - COALESCE((
          SELECT SUM(pbp.quantity_used)
          FROM public.production_batch_parts pbp
          WHERE pbp.part_batch_id IN (SELECT id FROM public.part_batches WHERE part_id = p.id)
        ), 0)
        FROM public.part_batches pb
        WHERE pb.part_id = p.id AND NOT pb.is_blocked
      ), 0),
      'batches', COALESCE((
        SELECT jsonb_agg(jsonb_build_object(
          'part_batch_id', pb.id,
          'batch_number', pb.batch_number,
          'quantity', pb.quantity,
          'remaining', pb.quantity - COALESCE((
            SELECT SUM(pbp.quantity_used)
            FROM public.production_batch_parts pbp
            WHERE pbp.part_batch_id = pb.id
          ), 0),
          'created_at', pb.created_at
        ) ORDER BY pb.created_at)
        FROM public.part_batches pb
        WHERE pb.part_id = p.id AND NOT pb.is_blocked
      ), '[]'::jsonb)
    ) AS row
    FROM public.parts p
    WHERE p.id = ANY(p_part_ids)
  ) s;
$$;

GRANT EXECUTE ON FUNCTION public.get_part_availability(UUID[]) TO authenticated;